// End-to-end walkthrough of RateMyWAF (sample data mode) in headless Chromium.
import { chromium } from 'playwright';
import path from 'node:path';

const base = 'http://localhost:5210';
import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const outDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'screenshots');
mkdirSync(outDir, { recursive: true });
const errors = [];
let step = 0;

const browser = await chromium.launch({ executablePath: process.env.PW_EXE || undefined });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: 'light' });
page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message));

async function shot(name) {
  step++;
  const file = path.join(outDir, `${String(step).padStart(2, '0')}-${name}.png`);
  await page.screenshot({ path: file, fullPage: true });
  console.log('shot', file);
}
async function expectText(text) {
  try {
    await page.getByText(text, { exact: false }).first().waitFor({ timeout: 10000 });
    console.log('  ok:', text);
  } catch (e) {
    await shot('failure');
    console.log('URL:', page.url());
    console.log('PAGE TEXT:', (await page.locator('body').innerText()).slice(0, 2000));
    throw e;
  }
}

// Home
await page.goto(base);
await expectText('How good is your Azure WAF?');
await shot('home');

// Enter sample data mode -> Front Door scope
await page.getByRole('button', { name: /Try with sample data/ }).click();
await page.waitForURL(/front-door/);
await expectText('Choose what to scan');
await page.locator('li.sub-row').first().waitFor();
await page.locator('.sub-count.has').first().waitFor({ timeout: 10000 });
await shot('fd-scope');

// Select all relevant and scan
await page.getByRole('button', { name: /Select all with Front Doors/ }).click();
const scanBtn = page.getByRole('button', { name: /^Scan 2 subscriptions/ });
await scanBtn.waitFor();
await scanBtn.click();
await page.waitForURL(/front-door\/grades/, { timeout: 20000 });
await expectText('Findings');
const overall = await page.locator('.overall .grade-badge.lg').textContent();
console.log('  Front Door overall grade:', overall);
if (overall !== 'E') throw new Error('expected overall E, got ' + overall);
const ratingCount = await page.locator('article.rating').count();
console.log('  ratings:', ratingCount);
await shot('fd-grades');

// Expand a collapsed rating and a finding fix, then a policy row
await page.locator('article.rating:not(.open) .rating-row').first().click();
await expectText('Score breakdown');
await page.locator('ul.findings li button.link').first().click();
await page.locator('.fix').first().waitFor();
await page.locator('tr.policy-row').first().click();
await page.locator('.policy-detail').first().waitFor();
await shot('fd-grades-expanded');

// Report modal
await page.getByRole('button', { name: /Summary report/ }).first().click();
await expectText('Summary Report');
await page.getByRole('button', { name: 'Detailed findings' }).click();
await expectText('Detailed Findings');
await shot('fd-report');
await page.locator('.modal-head .icon-btn').click();

// Logs step
await page.getByRole('link', { name: /Analyse logs/ }).first().click();
await page.waitForURL(/front-door\/logs/);
await expectText('Analyse the WAF logs');
await page.getByRole('button', { name: /Analyse logs/ }).click();
await page.locator('article.activity').first().waitFor({ timeout: 15000 });
await expectText('Alert assessment');
await expectText('Likely real attack');
await expectText('Possible false positive');
await expectText('Needs review');
await shot('fd-logs');

// Changes modal + fix script modal
await page.getByRole('button', { name: /Changes vs previous period/ }).click();
await expectText('Started triggering this period');
await page.locator('.modal-head .icon-btn').click();
await page.locator('article.activity button.btn').first().click();
await expectText('generated by RateMyWAF');
await shot('fd-fix-script');
await page.locator('.modal-head .icon-btn').click();

// Step bar navigation back to grades keeps state
await page.locator('.stepbar a[href="/front-door/grades"]').click();
await page.waitForURL(/front-door\/grades/);
await expectText('Findings');

// Application Gateway flow via the top tab
await page.getByRole('link', { name: /Application Gateway WAFs/ }).click();
await page.waitForURL(/app-gateway/);
await expectText('Choose what to scan');
await page.locator('.sub-count.has').first().waitFor({ timeout: 10000 });
await page.getByRole('button', { name: /Select all with Application Gateways/ }).click();
await page.getByRole('button', { name: /^Scan 2 subscriptions/ }).click();
await page.waitForURL(/app-gateway\/grades/, { timeout: 20000 });
const gwOverall = await page.locator('.overall .grade-badge.lg').textContent();
console.log('  App Gateway overall grade:', gwOverall);
if (gwOverall !== 'F') throw new Error('expected overall F, got ' + gwOverall);
await expectText('legacy inline');
await expectText('does not support the Web Application Firewall');
await shot('agw-grades');

await page.getByRole('link', { name: /Analyse logs/ }).first().click();
await page.waitForURL(/app-gateway\/logs/);
await page.getByRole('button', { name: /Analyse logs/ }).click();
await page.locator('article.activity').first().waitFor({ timeout: 15000 });
await page.locator('article.activity button.btn').first().click();
await expectText('Az.Network');
await shot('agw-fix-script');
await page.locator('.modal-head .icon-btn').click();

// The Front Door flow's state survived while we used the other flow
await page.getByRole('link', { name: /Front Door WAFs/ }).click();
await page.waitForURL(/front-door$/);
await expectText('Back to grades');

// Dark theme toggle
await page.locator('.topbar .icon-btn').click();
const theme = await page.evaluate(() => document.documentElement.getAttribute('data-theme'));
console.log('  theme after toggle:', theme);
// A hard reload drops the circuit (and the in-memory scan): the wizard must fall back to Scope,
// with the subscription selection restored from sessionStorage, so one click rescans.
await page.goto(base + '/front-door/grades');
await expectText('Choose what to scan');
const restored = page.getByRole('button', { name: /^Scan 2 subscriptions/ });
await restored.waitFor({ timeout: 10000 });
console.log('  selection restored after reload');
await restored.click();
await page.waitForURL(/front-door\/grades/, { timeout: 20000 });
await expectText('Findings');
await shot('fd-grades-dark');

// Mobile viewport
await page.setViewportSize({ width: 420, height: 900 });
await page.getByRole('link', { name: /Application Gateway WAFs/ }).click();
await page.waitForURL(/app-gateway/);
await page.getByRole('button', { name: /^Scan 2 subscriptions/ }).click();
await page.waitForURL(/app-gateway\/grades/, { timeout: 20000 });
try {
  await expectText('WAF policies');
} catch (e) {
  await shot('failure');
  console.log('PAGE TEXT:', (await page.locator('main').innerText()).slice(0, 1500));
  throw e;
}
await shot('agw-grades-mobile');

await browser.close();
if (errors.length) {
  console.log('BROWSER ERRORS:\n' + errors.join('\n'));
  process.exit(1);
}
console.log('E2E OK');
