using System.Text;
using RateMyWaf.Models;

namespace RateMyWaf.Services;

/// <summary>Generates PowerShell (Az module) remediation scripts for a rule activity, for either product.</summary>
public static class FixScriptService
{
    public sealed record FixOption(string Key, string Label, bool Enabled);

    /// <summary>Explanation and default options for an activity's classification.</summary>
    public static (string Explanation, List<FixOption> Options) Describe(WafRuleActivity a, WafFlowKind flow)
    {
        var product = flow.Label();
        var hasMatchVar = !string.IsNullOrEmpty(a.SampleMatchVariable);

        if (a.Classification == "Possible false positive")
            return ($"Adds a managed-rule exclusion for rule '{a.RuleName}' on {product} policy '{a.PolicyName}'. " +
                    "This stops the rule from inspecting the matched variable/selector so legitimate traffic is no longer blocked, " +
                    "while the rule continues to protect all other request fields.",
                [
                    new("exclusion", "Add managed-rule exclusion", true),
                    new("scopeUri", "Note the matched URI pattern in the script", a.SampleUris.Count > 0),
                ]);

        if (a.Classification == "Likely real attack")
            return ($"Creates a custom block rule to proactively deny traffic matching the attack pattern seen on rule '{a.RuleName}'. " +
                    "Useful for IP-based blocking of repeat offenders ahead of the managed rule set.",
                [
                    new("blockIp", "Block sample source IPs with a custom rule", a.SampleIps.Count > 0),
                    new("enablePrevention", "Switch policy to Prevention mode (if Detection)", true),
                ]);

        return ($"Switches the policy to Detection mode so you can observe the traffic pattern for rule '{a.RuleName}' " +
                "without blocking, then decide whether to add an exclusion or leave the rule active.",
            [
                new("detectionMode", "Set policy to Detection mode temporarily", true),
                new("exclusion", "Add managed-rule exclusion", hasMatchVar),
            ]);
    }

    public static string Generate(WafRuleActivity a, WafFlowKind flow, IEnumerable<FixOption> options)
    {
        var enabled = options.Where(o => o.Enabled).Select(o => o.Key).ToHashSet();
        return flow == WafFlowKind.FrontDoor ? GenerateFrontDoor(a, enabled) : GenerateAppGateway(a, enabled);
    }

    private static string Header(WafRuleActivity a, string module)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# WAF fix script — generated by RateMyWAF");
        sb.AppendLine($"# Rule: {a.RuleName}");
        sb.AppendLine($"# Policy: {a.PolicyName}");
        sb.AppendLine($"# Classification: {a.Classification}");
        sb.AppendLine();
        sb.AppendLine("# ─── Prerequisites ───");
        sb.AppendLine($"# Requires the {module} PowerShell module. Run Connect-AzAccount first.");
        sb.AppendLine("# Review every line before running: this script CHANGES the WAF policy.");
        sb.AppendLine();
        sb.AppendLine($"$policyName = \"{a.PolicyName}\"");
        sb.AppendLine("$resourceGroup = \"<YOUR-RESOURCE-GROUP>\"  # <- update this");
        sb.AppendLine();
        return sb.ToString();
    }

    private static (string Variable, string Selector) ExclusionTarget(WafRuleActivity a, string defaultVariable)
    {
        var matchVar = !string.IsNullOrEmpty(a.SampleMatchVariable) ? a.SampleMatchVariable : defaultVariable;
        var idx = matchVar.IndexOf(':');
        var selector = "*";
        if (idx > 0 && idx < matchVar.Length - 1)
        {
            selector = matchVar[(idx + 1)..].Trim();
            matchVar = matchVar[..idx];
        }
        else if (!string.IsNullOrEmpty(a.SampleMatchData))
        {
            selector = a.SampleMatchData.Split(' ').FirstOrDefault() ?? "*";
        }
        return (matchVar.Trim(), selector);
    }

    private static string GenerateFrontDoor(WafRuleActivity a, HashSet<string> enabled)
    {
        var sb = new StringBuilder(Header(a, "Az.FrontDoor"));
        var ruleId = WafLogAnalysisService.ExtractRuleId(a.RuleName);

        if (enabled.Contains("exclusion"))
        {
            var (variable, selector) = ExclusionTarget(a, "RequestHeaderNames");
            sb.AppendLine("# ─── Add a managed-rule exclusion scoped to this rule ───");
            if (enabled.Contains("scopeUri") && a.SampleUris.Count > 0)
            {
                var uri = a.SampleUris[0];
                sb.AppendLine($"# Seen on URI: {(uri.Contains('?') ? uri.Split('?')[0] : uri)}");
            }
            sb.AppendLine($"$ruleId = \"{ruleId}\"");
            sb.AppendLine($"$exclusion = New-AzFrontDoorWafManagedRuleExclusionObject -Variable \"{variable}\" -Operator Equals -Selector \"{selector}\"");
            sb.AppendLine();
            sb.AppendLine("$policy = Get-AzFrontDoorWafPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("$drs = $policy.ManagedRules | Where-Object { $_.RuleSetType -like '*DefaultRuleSet*' } | Select-Object -First 1");
            sb.AppendLine("$group = $drs.RuleGroupOverrides | Where-Object { $_.ManagedRuleOverrides.RuleId -contains $ruleId } | Select-Object -First 1");
            sb.AppendLine("if (-not $group) {");
            sb.AppendLine("    # The rule is not overridden yet: create an override that keeps it enabled and attaches the exclusion.");
            sb.AppendLine("    $groupName = Read-Host \"Rule group name for rule $ruleId (e.g. SQLI, XSS, PROTOCOL-ATTACK)\"");
            sb.AppendLine("    $override = New-AzFrontDoorWafManagedRuleOverrideObject -RuleId $ruleId -EnabledState Enabled -Exclusion $exclusion");
            sb.AppendLine("    $group = New-AzFrontDoorWafRuleGroupOverrideObject -RuleGroupName $groupName -ManagedRuleOverride $override");
            sb.AppendLine("    $drs.RuleGroupOverrides += $group");
            sb.AppendLine("} else {");
            sb.AppendLine("    ($group.ManagedRuleOverrides | Where-Object RuleId -eq $ruleId).Exclusions += $exclusion");
            sb.AppendLine("}");
            sb.AppendLine("Update-AzFrontDoorWafPolicy -InputObject $policy -ManagedRule $policy.ManagedRules");
            sb.AppendLine();
        }

        if (enabled.Contains("blockIp") && a.SampleIps.Count > 0)
        {
            sb.AppendLine("# ─── Block the sample source IPs with a custom rule ───");
            sb.AppendLine($"$blockIps = @({string.Join(", ", a.SampleIps.Take(5).Select(ip => $"\"{ip}\""))})");
            sb.AppendLine("$condition = New-AzFrontDoorWafMatchConditionObject -MatchVariable RemoteAddr -OperatorProperty IPMatch -MatchValue $blockIps");
            sb.AppendLine($"$rule = New-AzFrontDoorWafCustomRuleObject -Name \"Block_{SafeName(ruleId)}\" -RuleType MatchRule -MatchCondition $condition -Action Block -Priority 100");
            sb.AppendLine("$policy = Get-AzFrontDoorWafPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("Update-AzFrontDoorWafPolicy -InputObject $policy -Customrule (@($policy.CustomRules) + $rule)");
            sb.AppendLine();
        }

        if (enabled.Contains("enablePrevention"))
        {
            sb.AppendLine("# ─── Switch to Prevention mode ───");
            sb.AppendLine("Update-AzFrontDoorWafPolicy -Name $policyName -ResourceGroupName $resourceGroup -Mode Prevention");
            sb.AppendLine();
        }

        if (enabled.Contains("detectionMode"))
        {
            sb.AppendLine("# ─── Switch to Detection mode (observe without blocking) ───");
            sb.AppendLine("Update-AzFrontDoorWafPolicy -Name $policyName -ResourceGroupName $resourceGroup -Mode Detection");
            sb.AppendLine();
        }

        if (enabled.Count == 0)
            sb.AppendLine("# No options selected — toggle the options above to generate a script.");

        sb.AppendLine("Write-Host \"Done — policy '$policyName' updated.\" -ForegroundColor Green");
        return sb.ToString();
    }

    private static string GenerateAppGateway(WafRuleActivity a, HashSet<string> enabled)
    {
        var sb = new StringBuilder(Header(a, "Az.Network"));
        var ruleId = WafLogAnalysisService.ExtractRuleId(a.RuleName);

        if (enabled.Contains("exclusion"))
        {
            var (variable, selector) = ExclusionTarget(a, "RequestHeaderNames");
            sb.AppendLine("# ─── Add a per-rule exclusion (rule stays enabled everywhere else) ───");
            if (enabled.Contains("scopeUri") && a.SampleUris.Count > 0)
            {
                var uri = a.SampleUris[0];
                sb.AppendLine($"# Seen on URI: {(uri.Contains('?') ? uri.Split('?')[0] : uri)}");
            }
            sb.AppendLine($"$ruleId = \"{ruleId}\"");
            sb.AppendLine("$policy = Get-AzApplicationGatewayFirewallPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("$ruleSet = $policy.ManagedRules.ManagedRuleSets | Select-Object -First 1");
            sb.AppendLine("$groupName = Read-Host \"Rule group name for rule $ruleId (e.g. REQUEST-942-APPLICATION-ATTACK-SQLI)\"");
            sb.AppendLine("$ruleEntry = New-AzApplicationGatewayFirewallPolicyExclusionManagedRule -RuleId $ruleId");
            sb.AppendLine("$groupEntry = New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleGroup -Name $groupName -Rule $ruleEntry");
            sb.AppendLine("$exclSet = New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleSet -Type $ruleSet.RuleSetType -Version $ruleSet.RuleSetVersion -RuleGroup $groupEntry");
            sb.AppendLine($"$exclusion = New-AzApplicationGatewayFirewallPolicyExclusion -MatchVariable \"{variable}\" -SelectorMatchOperator Equals -Selector \"{selector}\" -ExclusionManagedRuleSet $exclSet");
            sb.AppendLine("$policy.ManagedRules.Exclusions += $exclusion");
            sb.AppendLine("Set-AzApplicationGatewayFirewallPolicy -InputObject $policy");
            sb.AppendLine();
        }

        if (enabled.Contains("blockIp") && a.SampleIps.Count > 0)
        {
            sb.AppendLine("# ─── Block the sample source IPs with a custom rule ───");
            sb.AppendLine($"$blockIps = @({string.Join(", ", a.SampleIps.Take(5).Select(ip => $"\"{ip}\""))})");
            sb.AppendLine("$variable = New-AzApplicationGatewayFirewallMatchVariable -VariableName RemoteAddr");
            sb.AppendLine("$condition = New-AzApplicationGatewayFirewallCondition -MatchVariable $variable -Operator IPMatch -MatchValue $blockIps");
            sb.AppendLine($"$rule = New-AzApplicationGatewayFirewallCustomRule -Name \"Block_{SafeName(ruleId)}\" -Priority 10 -RuleType MatchRule -MatchCondition $condition -Action Block");
            sb.AppendLine("$policy = Get-AzApplicationGatewayFirewallPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("$policy.CustomRules += $rule");
            sb.AppendLine("Set-AzApplicationGatewayFirewallPolicy -InputObject $policy");
            sb.AppendLine();
        }

        if (enabled.Contains("enablePrevention"))
        {
            sb.AppendLine("# ─── Switch to Prevention mode ───");
            sb.AppendLine("$policy = Get-AzApplicationGatewayFirewallPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("$policy.PolicySettings.Mode = \"Prevention\"");
            sb.AppendLine("Set-AzApplicationGatewayFirewallPolicy -InputObject $policy");
            sb.AppendLine();
        }

        if (enabled.Contains("detectionMode"))
        {
            sb.AppendLine("# ─── Switch to Detection mode (observe without blocking) ───");
            sb.AppendLine("$policy = Get-AzApplicationGatewayFirewallPolicy -Name $policyName -ResourceGroupName $resourceGroup");
            sb.AppendLine("$policy.PolicySettings.Mode = \"Detection\"");
            sb.AppendLine("Set-AzApplicationGatewayFirewallPolicy -InputObject $policy");
            sb.AppendLine();
        }

        if (enabled.Count == 0)
            sb.AppendLine("# No options selected — toggle the options above to generate a script.");

        sb.AppendLine("Write-Host \"Done — policy '$policyName' updated.\" -ForegroundColor Green");
        return sb.ToString();
    }

    private static string SafeName(string s) =>
        new string(s.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
}
